---
abstract: 'BeLike::GENEHACK when you zilla your dist'
author:
  - 'John SJ Anderson <genehack@genehack.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300014, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-GENEHACK
requires:
  Dist::Zilla: 0
  Dist::Zilla::Plugin::ArchiveRelease: 0
  Dist::Zilla::Plugin::Authority: 0
  Dist::Zilla::Plugin::AutoPrereqs: 0
  Dist::Zilla::Plugin::Bugtracker: 0
  Dist::Zilla::Plugin::CheckChangesHasContent: 0
  Dist::Zilla::Plugin::EOLTests: 0
  Dist::Zilla::Plugin::ExtraTests: 0
  Dist::Zilla::Plugin::Git::NextVersion: 0
  Dist::Zilla::Plugin::GithubMeta: 0
  Dist::Zilla::Plugin::Homepage: 0
  Dist::Zilla::Plugin::InstallGuide: 0
  Dist::Zilla::Plugin::InstallRelease: 0
  Dist::Zilla::Plugin::MetaConfig: 0
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MinimumPerl: 0
  Dist::Zilla::Plugin::NextRelease: 0
  Dist::Zilla::Plugin::PkgVersion: 0
  Dist::Zilla::Plugin::PodCoverageTests: 0
  Dist::Zilla::Plugin::PodSyntaxTests: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::ReadmeMarkdownFromPod: 0
  Dist::Zilla::Plugin::Repository: 0
  Dist::Zilla::Plugin::TaskWeaver: 0
  Dist::Zilla::Plugin::Test::Compile: 0
  Dist::Zilla::Plugin::Test::Kwalitee: 0
  Dist::Zilla::Plugin::Twitter: 0
  Dist::Zilla::PluginBundle::Basic: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
  Pod::Elemental::Transformer::List: 0
  namespace::autoclean: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-GENEHACK
  homepage: http://search.cpan.org/dist/Dist-Zilla-PluginBundle-GENEHACK/
  repository: git://github.com/genehack/dist-zilla-pluginbundle-genehack.git
version: 0.5
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@GENEHACK/@Git/Check'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@GENEHACK/@Git/Commit'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@GENEHACK/@Git/Tag'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@GENEHACK/@Git/Push'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@GENEHACK/Git::NextVersion'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@GENEHACK/@Basic/GatherDir'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@GENEHACK/@Basic/PruneCruft'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@GENEHACK/@Basic/ManifestSkip'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@GENEHACK/@Basic/MetaYAML'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::License
      name: '@GENEHACK/@Basic/License'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@GENEHACK/@Basic/Readme'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@GENEHACK/@Basic/ExtraTests'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@GENEHACK/@Basic/ExecDir'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@GENEHACK/@Basic/ShareDir'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@GENEHACK/@Basic/MakeMaker'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@GENEHACK/@Basic/Manifest'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@GENEHACK/@Basic/TestRelease'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@GENEHACK/@Basic/ConfirmRelease'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@GENEHACK/@Basic/UploadToCPAN'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@GENEHACK/AutoPrereqs'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@GENEHACK/CheckChangesHasContent'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@GENEHACK/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@GENEHACK/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@GENEHACK/PkgVersion'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@GENEHACK/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@GENEHACK/Bugtracker'
      version: 1.111080
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@GENEHACK/Homepage'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@GENEHACK/MetaConfig'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@GENEHACK/MetaJSON'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@GENEHACK/Repository'
      version: 0.18
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@GENEHACK/InstallGuide'
      version: 1.101461
    -
      class: Dist::Zilla::Plugin::ReadmeMarkdownFromPod
      name: '@GENEHACK/ReadmeMarkdownFromPod'
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@GENEHACK/CopyFilesFromBuild'
      version: 0.103510
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@GENEHACK/NextRelease'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@GENEHACK/ExtraTests'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@GENEHACK/PodCoverageTests'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@GENEHACK/PodSyntaxTests'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@GENEHACK/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@GENEHACK/Test::Compile'
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      name: '@GENEHACK/Test::Kwalitee'
      version: 2.03
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@GENEHACK/Twitter'
      version: 0.015
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@GENEHACK/Git::Commit'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@GENEHACK/Git::Tag'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@GENEHACK/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: '@GENEHACK/ArchiveRelease'
      version: 4.00
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300014
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300014
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300014
x_authority: cpan:GENEHACK
